### ISSUE TITLE
Améliorer la compréhension des règles

### ISSUE THREAD

**Issue by laem** [sgmap/syso#11]
Sur /regle

- [x] injecter les valeurs par défaut pour plus de simplicité, bouton "cacher mes valeurs" plus discret
Avant ça, il faut un meilleur affichage des valeurs : booléens, ne pas arrondir si agressivement etc.
- [x] revoir l'agencement de la page : c'est très flottant et brouillon aujourd'hui, la section 'formule' n'est pas bien identifiée etc.

**Comment by Morendil** [comment]
- [ ] Pouvoir naviguer ("drill down") vers les règles appelées pour calculer une valeur

**Comment by laem** [comment]
Ajourd'hui, la simulation /simu/:variable affichera dans la barre de résultats en bas une liste de résultats si c'est une somme, ou un résultat unique sinon. 

Quand on y réfléchit, ce qu'on veut vraiment dans cette barre de résultat, c'est : 
- un résumé, résultat simple de la simulation
- un moyen de comprendre / décomposer ce résultat, ce qui revient finalement à ta proposition pour la page /regle !
Il faut donc travailler l'unification de la formule sur /regle <Rule /> et de la barre de résultats <Results />, qui sont pour l'instant deux codes séparés.

**Comment by Morendil** [comment]
Nettement amélioré, je ferme en faveur d'issues plus ciblées à extraire de réflexions ou tests à venir.
