### ISSUE TITLE
Ne pas avoir à cliquer "J'ai compris" en reprise de simulation

### ISSUE THREAD

**Issue by Morendil** [sgmap/syso#120]
Actuellement, quand on part vers une page règle et qu'on clique sur "Reprendre", on est à nouveau confronté à l'avertissement sur le CDD et on doit cliquer sur "J'ai compris" pour avoir à nouveau accès aux questions.

Bug détecté en reproduisant un parcours usager ayant conduit à un :|

**Comment by laem** [comment]
Ce bug n'est plus pertinent.
