### ISSUE TITLE
Position de la question "événements de contrat CDD"

### ISSUE THREAD

**Issue by laem** [sgmap/syso#22]
Suite de notre discussion @Morendil @georges-bayard. 

Le problème :
> la première question du simulateur CDD beta est perturbante, car elle parle d'événements de contrat qui sont improbables surtout pour la personne indécise qui réfléchit à une embauche (contrairement à l'employeur ou le salaié qui a déjà signé un contrat CDD en cours) et ce avant de parler du salaire, du motif. 

Une des solutions proposées est de transformer cette question en : 
```
Première question : 
- J’envisage un recrutement en CDD 
- Le CDD est en cours et l’une des situations suivantes se présente
        Poursuite du CDD en CDI
        Refus d'un CDI avantageux
        Rupture anticipée du salarié
        Rupture pour faute grave ou force majeure
        Rupture pendant la période d'essai
```

-------------

Je pense que l'on se trompe en voulant introduire la notion "j'envisage un recrutement / j'ai déjà recruté". Notre modèle de la loi doit rester éloigné de ces considérations. Il doit proposer un simulateur qui calcule le coût d'un contrat, et libre à l'utilisateur de se projeter dans le rôle d'un employeur ayant signé un contrat. 

On peut remarquer qu'il y a (au moins) deux catégories de questions aujourd'hui dans la simulation : celles qui permettent de définir les termes du contrat, donc en code de remplir les `attributs` de l'entité contrat, _lors de sa création_ et d'autres qui permettent de renseigner des _éventualités_, qui _surviendront par la suite_ :  des `événements` de contrat, qui vont venir le modifier. 

> On peut aussi imaginer que l'événement "le salarié devient cadre" survienne après la signature du contrat... mais c'est un attribut qui aurait pu être défini lors de la création du contrat, il a simplement été changé. 

L'interface serait alors modifiée en deux catégories de questions, bien explicites : 
- attributs du contrat
- événements de contrat

Par example : 
![dessin](https://user-images.githubusercontent.com/1177762/28622330-782c06ea-7214-11e7-9f77-ae40751e2884.jpg)

Du coup, de la même façon qu'on décore des variables comme étant des `cotisations`, ici ça deviendrait un `événement`, toujours attaché au contrat par son espace de nom, ce qui lui donnerait une priorité moindre par rapport aux attributs du contrat. 

Dans cette solution, des réponses de fin de simulation peuvent rendre inutiles les réponses d'avant, elles "cassent" la simulation en mettant tous les résultats à "ne vous concerne pas", ce qui me déplaisait (impression d'avoir perdu son temps). 
Seulement, je me rends compte maintenant qu'il y a aussi un intérêt pour l'utilisateur à s'être rendu compte qu'_avant_ de répondre "CDD poursuivi en CDI" il aurait du payer 300€, et qu'_après_ ce n'est pas le cas. On retrouve ici la valeur du jeu de simulation où l'utilisateur comprend les variations de résultat en conséquence des réponses aux questions, et cette valeur peut être plus importante que la potentielle perte de temps.

**Comment by georges-bayard** [comment]
Je crains que la notion de contrat n'apporte pas grand chose à l'utilisateur final et le trouble. Tu le dis toi même un évènement prévu initialement dans le contrat (changement de statut de non cadre à cadre) peut évoluer à n'importe quel moment moment en cours de contrat. Si tu tiens à cette notion parce qu'elle colle à ton modèle il faudra à mon sens faire une surcouche pour la masquer.
Il me semble qu'il y a deux notions très différentes et à séparer : la notion d'événement (je veux recruter, des évènements en cours viennent modifier le cours des choses, ...) qui permet de sélectionner les questions à poser à l'utilisateur. Quand on a bien défini ce cadre  à on peut alors poser des questions à l'utilisateur permettant de qualifier l'événement.
J'irais même plus loin : on pourrait avoir 3 natures de questions : qui es tu (entreprise, salarié) qualifié précisément la situation dans laquelle tu te situe, décris moi ta situation

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

26 juil. 2017 15:22:00, Mael <notifications@github.com> a écrit :



Suite de notre discussion @Morendil<https://github.com/morendil> @georges-bayard<https://github.com/georges-bayard>.

Le problème :

la première question du simulateur CDD beta est perturbante, car elle parle d'événements de contrat qui sont improbables surtout pour la personne indécise qui réfléchit à une embauche (contrairement à l'employeur ou le salaié qui a déjà signé un contrat CDD en cours) et ce avant de parler du salaire, du motif.

Une des solutions proposées est de transformer cette question en :

Première question :
- J’envisage un recrutement en CDD
- Le CDD est en cours et l’une des situations suivantes se présente
        Poursuite du CDD en CDI
        Refus d'un CDI avantageux
        Rupture anticipée du salarié
        Rupture pour faute grave ou force majeure
        Rupture pendant la période d'essai


________________________________

Je pense que l'on se trompe en voulant introduire la notion "j'envisage un recrutement / j'ai déjà recruté". Notre modèle de la loi doit rester éloigné de ces considérations. Il doit proposer un simulateur qui calcule le coût d'un contrat, et libre à l'utilisateur de se projeter dans le rôle d'un employeur ayant signé un contrat.

On peut remarquer qu'il y a (au moins) deux catégories de questions aujourd'hui dans la simulation : celles qui permettent de définir les termes du contrat, donc en code de remplir les attributs de l'entité contrat, lors de sa création et d'autres qui permettent de renseigner des éventualités, qui surviendront par la suite : des événements de contrat, qui vont venir le modifier.

On peut aussi imaginer que l'événement "le salarié devient cadre" survienne après la signature du contrat... mais c'est un attribut qui aurait pu être défini lors de la création du contrat, il a simplement été changé.

L'interface serait alors modifiée en deux catégories de questions, bien explicites :

  *   attributs du contrat
  *   événements de contrat

Par example :
[dessin]<https://user-images.githubusercontent.com/1177762/28622330-782c06ea-7214-11e7-9f77-ae40751e2884.jpg>

Du coup, de la même façon qu'on décore des variables comme étant des cotisations, ici ça deviendrait un événement, toujours attaché au contrat par son espace de nom, ce qui lui donnerait une priorité moindre par rapport aux attributs du contrat.

**Comment by laem** [comment]
@georges-bayard est-ce que tu peux répondre directement sur github.com ? Ou si tu réponds par mail trouve un moyen de ne pas citer toute la discussion précédente ça trouve la conversation


> Je crains que la notion de contrat n'apporte pas grand chose à l'utilisateur final et le trouble.

Il faut que tu m'expliques pourquoi : on parle bien de quelqu'un qui a ou veut embaucher en CDD. Il devra forcément ou a déjà signé un contrat contenant précisément ces éléments : salaire, motif etc. 

Je maintiens qu'il ne faut que l'on évite d'afficher dans l'UI les considérations du genre "je compte embaucher ou j'ai déjà embauché". Ça nous apporte de la complexité, sans impact sur le calcul : il ne faut pas l'introduire dans le modèle. Pour l'utilisateur surtout, ce n'est pas parce qu'il n'a pas encore embauché qu'il faut que l'on lui cache ce qui arrivera dans l'éventualité des événements de contrat !

Même remarque je crois pour ce point-là : 

> J'irais même plus loin : on pourrait avoir 3 natures de questions : qui es tu (entreprise, salarié) qualifié précisément la situation dans laquelle tu te situe, décris moi ta situation

Ce n'est pas parce que je suis un salarié que je ne peux être intéressé par la simulation des charges patronales. Et vice versa. L'important c'est qu'en amont de la simulation je choisisse des _objectifs_ comme le salaire net. Donc que je choisisse un simulateur (nos simulateurs calculent un objetif) dans une liste. 

Par contre, là où cette distinction sur la _personne derrière l'écran_ devient intéressante, c'est dans le type de simulation qu'il veut choisir. Je pense qu'un utilisateur qui veut embaucher voudra une simulation rapide, où l'on puisse lui dire à un moment "là tu as 90% de précision, tu peux t'arrêter si ça te va". Un utilisateur qui a déjà embauché aura plus tendance à choisir une simulation complète, où il faut tout remplir. Mais là aussi c'est le choix de simulation qu'il faut lui présenter : qu'est-ce que tu veux faire.

**Comment by georges-bayard** [comment]
Je suis sur mon mobile la.
Franchement je crains que cette discussion ne devienne rapidement stérile​. Elle ne peut être arbitrée à mon sens que par des retours utilisateurs c'est le seul juge de paix qui me semble fiable.
Jai un problème de méthode. Je comprends bien ta préoccupation de faire tout entrer dans un modèle pur ou tout est droit. Je crois plus à l'approche inverse : on invente un modèle qui réponde à un besoin. D'où la nécessité de ne pas traiter le point en petit comité

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

26 juil. 2017 16:59:57, Mael <notifications@github.com> a écrit :



@georges-bayard<https://github.com/georges-bayard> est-ce que tu peux répondre directement sur github.com ? Ou si tu réponds par mail trouve un moyen de ne pas citer toute la discussion précédente ça trouve la conversation

Je crains que la notion de contrat n'apporte pas grand chose à l'utilisateur final et le trouble.

Il faut que tu m'expliques pourquoi : on parle bien de quelqu'un qui a ou veut embaucher en CDD. Il devra forcément ou a déjà signé un contrat contenant précisément ces éléments : salaire, motif etc.

Je maintiens qu'il ne faut que l'on évite d'afficher dans l'UI les considérations du genre "je compte embaucher ou j'ai déjà embauché". Ça nous apporte de la complexité, sans impact sur le calcul : il ne faut pas l'introduire dans le modèle. Pour l'utilisateur surtout, ce n'est pas parce qu'il n'a pas encore embauché qu'il faut que l'on lui cache ce qui arrivera dans l'éventualité des événements de contrat !

Même remarque je crois pour ce point-là :

J'irais même plus loin : on pourrait avoir 3 natures de questions : qui es tu (entreprise, salarié) qualifié précisément la situation dans laquelle tu te situe, décris moi ta situation

Ce n'est pas parce que je suis un salarié que je ne peux être intéressé par la simulation des charges patronales. Et vice versa. L'important c'est qu'en amont de la simulation je choisisse des objectifs comme le salaire net. Donc que je choisisse un simulateur (nos simulateurs calculent un objetif) dans une liste.

Par contre, là où cette distinction sur la personne derrière l'écran devient intéressante, c'est dans le type de simulation qu'il veut choisir. Je pense qu'un utilisateur qui veut embaucher voudra une simulation rapide, où l'on puisse lui dire à un moment "là tu as 90% de précision, tu peux t'arrêter si ça te va". Un utilisateur qui a déjà embauché aura plus tendance à choisir une simulation complète, où il faut tout remplir. Mais là aussi c'est le choix de simulation qu'il faut lui présenter : qu'est-ce que tu veux faire.

**Comment by laem** [comment]
J'imagine qu'en supprimant le message cité dans ta réponse par mail ça 
marche. Je teste avec ce message pour voir.

Au contraire que l'on avance sur la discussion.

 > Je comprends bien ta préoccupation de faire tout entrer dans un 
modèle pur ou tout est droit.

Ce n'est pas du tout la préoccupation que j'ai (sinon j'aurais pas 
ouvert cette issue...). Mais un modèle cohérent (pas patché dans la 
hâte) et complet qui modélise fidèlement la loi et qui produit une 
interface adaptée.


 > Jai un problème de méthode.

Le fait de mettre cette question des événements en fin de simulation va 
justement dans le sens des retours utilisateurs.

Le truc c'est qu'on peut pas présenter dans une nouvelle version un hack 
graphique qui ne repose pas sur une vraie réflexion, notamment 
technique, car on ne construit pas une UI jetable.

**Comment by georges-bayard** [comment]
l'exemple que tu donnes sur le dessin est clair. Comment tu l'appliquerais au cas ou le salarié devient cadre ? dans ce cas je ne vois pas l'utilité de l'évènement. Il vaut mieux dans tous les cas faire la simulation en partant de la position cadre

**Comment by laem** [comment]
Pour moi le caractère cadre ou non cadre est un attribut du contrat. Il est présent lors de la définition de ce dernier. 

Donc si la simulation avait besoin de cette information (pas le cas pour l'instant dans le cas du CDD), la question apparaîtrait tout simplement comme le salaire. L'utilisateur peut simuler un changement de situation en revenant sur sa réponse (et bientôt juste en survolant le bouton de réponse pour voir les calculs impactés). 

Les événements ici ne sont pas des changements d'attributs écrits (ou qu'on pourrait écrire) dans le contrat (j'ai pas été clair plus haut) d'où leur séparation dans une autre "section".

**Comment by georges-bayard** [comment]
je crois qu'on est d'accord. Ca prouve qu'en dehors de l'exemple des évènements de rupture éventuelle du contrat on n'a pas d'autre exemple. Monter un concept avec un seul exemple ca me parait pas probant

**Comment by laem** [comment]
Oui c'est vraiment une réflexion en cours, pas si convainquante comme tu le soulignes :sweat: ...

**Comment by Morendil** [comment]
OK je vous propose de considérer la question comme traitée par la cinématique "Affiner votre situation", on pourra affiner avec des tests utilisateur. Je n'ai pas d'idée concrète sur la façon dont on peut intégrer cette notion d'événements au moteur, attendons de voir si on rencontre à nouveau une demande d'usager qui nous ramène vers ça.
