### ISSUE TITLE
 [BROUILLON] Feuille de route été

### ISSUE THREAD

**Issue by laem** [sgmap/syso#23]
Voilà à mon avis les développements qui me semblent prioritaires. 

@Morendil @georges-bayard c'est pour l'instant un brouillon, en cours de rédaction, je vous notifie quand j'ai quelque chose. On peut réfléchir à utiliser un kanban. 

![image](https://user-images.githubusercontent.com/1177762/28667024-fa368592-72c9-11e7-8754-9fa2944bbf89.png)

### Améliorations d'UX

Voir le ce point conséquent dans  #24

### Introduire des examples pour les mécanismes

Merci @Morendil pour tes super tests `traverse.test.js` et `variables.test.js`. 
Je pense qu'il faudra à côté de ces tests unitaires pouvoir lister une batterie de tests pour chaque mécanisme. 

Ces tests devraient être surtout conçus comme des examples destinés à être affichés dans la documentation lisible par tous d'un mécanisme sur la /regle (aujourd'hui un clic fait apparaître une description du fonctionnement du mécanisme

### Résoudre le problème de la question des événements
Voir #22

### Finaliser les cotisations 

@Morendil en a déjà traité un bon nombre

### Permettre le court-circuitage de la branche CDD

Pouvoir répondre "Non" à la question "le contrat est un CDD".
Je propose de jouer sur l'existence de l'entité CDD : tant qu'elle n'est pas instanciée, les variables d'objectif de son espace de nom sont ignorées. 

### Réfléchir crucial au bouton "Je ne sais pas"

Illustration : 
Pour calculer la cotisation AGIRC, nous avons besoin de l'assiette des cotisations sociales. Cette assiette est une variable qui n'a pas d'attribut `question` mais une formule : il faut donc la calculer. Dans un modèle simplifié elle vaut `salaire brut`, qui vaut à son tour `salaire de base + primes`. Mais `salaire brut` elle a la propriété `question`. On va donc la poser à l'utilisateur, **mais** accompagnée d'un bouton `[Je ne sais pas]` (texte à voir). Au clic, la formule est analysée, et on explique à l'utilisateur comment on va l'accompagner dans le calcul du salaire brut, en lui demandant le salaire de base et les primes. Ainsi de suite. 

Ce fonctionnement, qui est une "conversation descendante accompagnée" :laughing: , est discutable évidemment (l'opposé, qui est notre situation actuelle, étant de systématiquement poser les questions "feuilles" manquantes pour calculer les noeuds intermédiaires, jusqu'à l'objectif), mais je pense qu'accompagné d'une UX fluide, c'est optimal. 

### Refondre la section résultats

Elle devra afficher les 2 ou 3 objectifs aggregés de la simulation complète (salaire net, salaire super brut et "coût du travail" si ce dernier ne vient pas à disparaître avec les réformes Macron). 

Mais aussi inciter à l'exploration de ces résultats : lire les formules de lignes calculées qui constituent ces résultats aggrégés. 

Il faut remarquer qu'il n'y aura plus de différence entre la section "formule" de la page /regle : la barre de résultat n'est que la visualisation de la formule de l'objectif de la simulation ! Et un clic sur salaire net ne fait qu'afficher la formule du salaire net, c'est-à-dire la somme de toutes les cotisations salariales, elles aussi cliquables. 

> Il faudra gérer une version simplifiée des formules. Par example une cotisation de type taux * assiette peut voir son taux changer en fonction de l'effectif de l'entreprise : il faut alors présenter d'abord une version "résolue", simplifiée sans cet aiguillage sur le taux, et afficher la formule complète au clic.  

### Introduction des attributs `implication` et `contrôles` des variables

Là où formule exprime une équivalence, implication est une ... implication. 

Limites permet par example de dire qu'un salaire inférieur au SMIC n'est pas autorisé. 

> Et mieux : un salaire inférieur au SMIC n'est autorisé que dans des cas précis non pris en compte aujourd'hu dans l'application : à faire en connaissance de cause. Mieux encore : un salaire inférieur au SMIC en équivalent temps plein. Ce dernier example implique, on s'en serait douté, que les contrôles sont calculables.  

### Harmoniser le traitement des attributs des variables

Faire disparaître le statut particulier des attributs "formule" et "non applicable" d'une variable, par rapport au traitement des autres attributs d'une variable.

**Comment by georges-bayard** [comment]
Permettre le court-circuitage de la branche CDD en mettant non : ce serait pas mieux de mettre une liste de valeurs ?  ca ouvre la possibilité à d'autres types de contrats type contrat de chantier ... 

je ne saisis pas bien ton exemple cotisation AGIRC : tu veux remettre en cause le fait qu'on saisit un seul montant et le splitter en salaire de base et primes ? ca alourdit pas ? nous n'avons jamais eu cette remontée utilisateur

Sur l'affichage des taux tu crois qu'on pourrait aller jusqu'à afficher un taux par cotis comme sur la feuille de paye simplifiée ?

**Comment by laem** [comment]
> Permettre le court-circuitage de la branche CDD en mettant non : ce serait pas mieux de mettre une liste de valeurs ? ca ouvre la possibilité à d'autres types de contrats type contrat de chantier ...

Je ne connais pas le sujet des contrats de chantier : c'est quoi ? Mais en tout cas le CDD c'est bien un booléen : ton contrat (qui est par défaut un CDI) peut être un CDD ou non. Et c'est orthogonal par example avec le fait d'être un contrat d'apprentissage je crois. 



> je ne saisis pas bien ton exemple cotisation AGIRC : tu veux remettre en cause le fait qu'on saisit un seul montant et le splitter en salaire de base et primes ? ca alourdit pas ? nous n'avons jamais eu cette remontée utilisateur

Non justement, on garde le fonctionnement actuel en l'enrichissant : tu saisis un seul montant, le salaire brut. Par contre si tu as un doute sur ce que c'est, avec un nouveau bouton on te l'explique et on te guide : d'abord tu rentres le salaire régulier défini sur le contrat, puis les primes. On fait la somme pour toi.
Le sujet des primes est revenu très souvent dans les retours : "où je mets les primes ?"  


> Sur l'affichage des taux tu crois qu'on pourrait aller jusqu'à afficher un taux par cotis comme sur la feuille de paye simplifiée ?

Oui bien sûr c'est l'objectif :-) Enfin pour les barèmes, ex. retraite on informerais que c'est un barème qui peut être exploré au clic.

**Comment by laem** [comment]
Je ferme car ces points sont éclatés dans de nouvelles _issues_
