### ISSUE TITLE
Fourre-tout d'améliorations visuelles

### ISSUE THREAD

**Issue by laem** [sgmap/syso#24]
Améliorer l'expérience d'accueil d'un simulateur. D'après les discussion de @georges-bayard et @Morendil avec la DILA et nos designers. J'essaie d'en faire une synthèse ici. 

> Il manque aujourd'hui une structure de la page plus claire

- [x] Aligner la conversation avec son titre et le texte d'introduction. 
- [ ] Essayer de mettre la barre de résultat à droite verticalement. Attention : demande de revoir la version mobile, où c'est impossible. 
- [x] Les bulles d'aide :bulb: seraient alors déplacées à gauche sous ou au-dessus de la question en cours. 
- [ ] À l'initialisation, afficher une bulle d'aide qui explique le fonctionnement : "Répondez aux questions qui apparaissent jusqu'au panneau fin. Visualisez à tout moment l'impact de vos réponses sur vos résultats à droite".  
- [x] Réintroduire la barre de résultat à l'initialisation, mais en contrepartie rendre plus visibles ses mises à jour (flash visuel ?).
- [ ] Finaliser la PR qui introduit le calcul à la volée des résultats (pas besoin de choisir une réponse, simplement la renseigner sans valider ou survoler la proposition de réponse). 
- [ ] refermer la section "vos réponses", qui va s'ouvrir au clic. Demande le calcul à la volée des résultat ! 
- [ ] mettre les liens "non officiels" en retrait
- [ ] pouvoir expliquer pourquoi une question est posée : nous vous demandons l'effectif de l'entreprise parce qu'il est utilisé pour calculer le FNAL, le XX etc.

**Comment by georges-bayard** [comment]
Je ne retrouve pas dans la liste les points remontés par la DILA.

cf mon mail de CR du 20/07 qui porte beaucoup sur le sujet UX : 
La réunion avec Flavien, l’UX et l’expert Agile de la DILA s’est bien passée. Je leurs ai expliqué notre démarche (V1, V2 Beta, V3 co construite).

1 / Sur la V1 actuelle ils intègrent l’embed sur les pages SP sans attendre en début de semaine prochaine. Ils ont fait également des constats de dysfonctionnements qu’ils s’engagent à nous envoyer (en particulier lien de contact pas assez mis en évidence).

2 / Sur la V2 Beta j’ai dissipé beaucoup de leurs réticences en expliquant qu’on proposait d’intégrer sur SP un lien, et non un embed générateur de confusion entre le SP voie de communication gouvernementale officielle et une version Beta CDD pas encore tout à fait sèche. Ils adhèrent à cette démarche de séparation.

Nous avons donc également convenu qui nous n’intégrerions pas toutes leurs demandes. Je leur ai dit que je me retournerais vers vous pour voir ce que l’on pouvait faire à minima. Voici les remarques exprimées sur la version Beta.
•	« votre simulation est terminée » n’est pas clair. Il faudrait faire apparaître plus clairement l’information qu’il n’y a pas de surcout quand c’est le cas
•	La zone « fin de simulation » doit être mise à la fin
•	les résultats de la simulation ne sont pas suffisamment mis en valeur
•	le rappel du parcours déjà réalisé doit être mis sur le côté de la page car c’est une information secondaire. Je leurs ai rappelé qu’il faudrait réfléchir à ce sujet car nous avons une contrainte forte de largeur en mode embed
•	le bouton « tout effacer » ne fonctionne (bug)
•	les questions posées ressemblent à des boutons d’action et sont donc trop voyant ; il ne faudrait pas les encadrer  supprimer l’encadré. L’œil doit être attiré sur  l’endroit l’utilisateur doit agir et non sur la question
•	Le § du haut de page qui rappelle que les cas de recours aux CDD et met en garde contre les abus prend trop de place. Le mettre sur la page d’accueil par exemple
•	Les informations essentielles ne sont pas mises en avant : répondre aux questions + résultat obtenu
•	problème pour l’accès aux pages d’explication de l’algorithme :  pas intuitif
•	mettre en beaucoup plus clair et « partout » 
Globalement je trouve les demandes logiques. Elles devront nourrir notre réflexion sur la V3 qui pourrait, concernant l’affichage des résultats, s’articuler autour de 3 niveaux
•	un niveau super agrégé (« le recrutement coute globalement XXXX en super brut, brut et net)
•	un deuxième niveau d’information présenterait sur une page le détail des calculs de l’ensemble des rubriques qui concourent au résultat agrégé
•	un troisième niveau d’information permet de zoomer sur une rubrique en particulier pour voir comment celle-ci a été calculé (accès à l’algorithmes)
J’ai ressenti un certain enthousiasme de leurs part quand ils ont vu la qualité du travail sur le fond, ce qui a permis de relativiser ou tout du moins de replacer dans un contexte plus large leurs remarques sur l’UX.
Ils attendent néanmoins les corrections demandées minimales demandées par Bernard Robert pour intégrer le lien vers la Beta.

3 / Sur la V3 co construite, la démarche envisagée recueille leurs agrément. Ils ont l’air OK sur nos propositions de fonctionnement en cycle court, mode agile et équipe autonome. Ils ont ré insisté sur la nécessité de prendre en compte les contraintes d’accessibilité dès l’amont. Nous avons eu un débat sur «comment prendre en compte les contraintes d’accessibilité en mode Agile » qui ressemblait un peu à un débat que Laurent connait bien je crois sur le thème « comment prendre en compte les contraintes de sécurité en mode Agile ». Ils sont très ouverts sur la question et sont prêts à expérimenter des solutions innovantes ou nous ne couvririons pas 100 % des contraintes à la première itération

**Comment by laem** [comment]
Oui je sais je n'ai pas encore eu le temps de les ajouter, d'où le marquage BROUILLON. Et je ne trouve pas de solution simple à la plupart de ces points malheureusement. Il faudra qu'on se penche sur ces sujets lors d'une session de travail concrête.

**Comment by laem** [comment]
@Morendil @georges-bayard Comme convenu il faut qu'on avance sur ces questions lors de plusieurs sessions avec un designer

**Comment by Morendil** [comment]
Je pense que cette issue n'est plus pertinente, à revoir en prenant comme base la nouvelle UX/UI.
