### ISSUE TITLE
Amélioration du moteur

### ISSUE THREAD

**Issue by laem** [sgmap/syso#27]
Refonte en cours sur #19 : différer l'évaluation et le rendu JSX de l'étape de construction de l'AST

Réfléxions sur évolution de la technique fonctionnelle à utiliser ici : #20

**Comment by Morendil** [comment]
Je vais fermer cette issue en considérant que la refonte est terminée sur la techno actuelle, je ne sais pas encore vraiment quelle priorité il faut donner à une réécriture en Purescript (ou autre, mais à ce stade de mes réflexions c'est dans ce langage que je me sens capable de lancer le chantier).

En fait je suis un peu gêné par des "grosses" issues, il me semble que Github est plus approprié pour gérer une liste d'améliorations de grain plus fin, actionnables et bien décrites, qu'un·e contribut·eur·rice un peu à l'aise peut prendre tout·e seul·e et mener au bout. Les gros sujets de réflexion sont plutôt à traiter dans un Wiki, à mon sens.

Si ça te va @laem je fermerais bien #24 et #11 dans cet esprit.
