### ISSUE TITLE
Pouvoir répondre "Non" à la question est-ce un CDD

### ISSUE THREAD

**Issue by laem** [sgmap/syso#29]
Autrement dit, permettre le court-circuitage de la branche CDD

Je propose de jouer sur l'existence de l'entité CDD : tant qu'elle n'est pas instanciée, les variables d'objectif de son espace de nom sont ignorées.

**Comment by Morendil** [comment]
Comme expliqué dans #45 je commence à entrevoir une façon plus directe de résoudre ceci, et qui devrait je pense nous permettre d'y voir plus clair sur #21 et #22. Je vais créer une PR dans ce sens basée sur #25 - tenant compte également des retours utilisateurs qui nous disent que le "surcoût CDD" n'est pas forcément la notion qui correspond à leurs attentes.

Par contre une fois que le simulateur contient la question "CDD ou CDI" on va de facto pouvoir représenter le surcoût: il suffit de modifier la réponse à la question "type de contrat". Et là on commence à ouvrir un grand champ d'expérimentation en matière d'UX:  comment favoriser l'usage exploratoire du simulateur ! (On peut par exemple imaginer de désigner une simulation comme "baseline" et d'afficher une variable synthétique qui serait la différence avec la baseline : ça ferait apparaître le surcoût de façon chiffrée...)

**Comment by Morendil** [comment]
On y est :)
