### ISSUE TITLE
Évolution des cotisation de chômage

### ISSUE THREAD

**Issue by laem** [sgmap/syso#87]
https://www.urssaf.fr/portail/home/actualites/toute-lactualite-employeur/contributions-patronales-dassura.html

**Comment by georges-bayard** [comment]
On avait évoqué le point en avril ou mai dernier sans creuser plus que ça il me semble. Sur les 3 points voilà ce que j’en pense :


·         La mise en place d’une contribution exceptionnelle temporaire : ca a pas l’air complexe juste une modif temporaire de taux. a faire pour la V2 Syso et pour la la V1 open fisca

·         La suppression de la majoration de la contribution patronale d’assurance chômage due au titre des CDD d’une durée inférieure ou égale à 3 mois conclus pour accroissement temporaire d’activité : modifier Syso : on passe de 4 à 3 impacts du CDD sur la fiche de paye

·         La suppression de l’exonération temporaire de la contribution patronale d’assurance chômage en cas d’embauche en CDI d’un jeune de moins de 26 ans : à intégrer dans Syso et open fisca ? le problème c’est qu’il faut poser une question supplémentaire sur l’âge ?

Pas neutre tout ca

Georges



De : Mael [mailto:notifications@github.com]
Envoyé : mardi 10 octobre 2017 17:13
À : sgmap/syso
Cc : Subscribed
Objet : [***] [sgmap/syso] Évolution des cotisation de chômage (#87)


https://www.urssaf.fr/portail/home/actualites/toute-lactualite-employeur/contributions-patronales-dassura.html

**Comment by Morendil** [comment]
> le problème c’est qu’il faut poser une question supplémentaire sur l’âge ?

Si on n'a jamais intégré l'exonération, pour intégrer sa suppression il suffit de ne rien faire. 😄 

Il faudrait rajouter une question sur l'âge seulement si on veut (a posteriori) tenir compte de l'exonération pour les embauches déjà réalisées avant le 1/10. Je ne sais pas si ça vaut le coup.

**Comment by laem** [comment]
Oui on avait déjà repéré ces changements mais je les pensais pour 2018. 

> on passe de 4 à 3 impacts du CDD sur la fiche de paye

Non, la majoration reste d'actualité pour les CDD d'usage.

**Comment by georges-bayard** [comment]
Putain quelle merde !

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

10 oct. 2017 20:14:40, Mael <notifications@github.com> a écrit :


Oui on avait déjà repéré ces changements mais je les pensais pour 2018.

on passe de 4 à 3 impacts du CDD sur la fiche de paye

Non, la majoration reste d'actualité pour les CDD d'usage.

**Comment by georges-bayard** [comment]
Ok ok. Prostituée quel excrément alors

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

10 oct. 2017 20:21:41, Laurent Bossavit <notifications@github.com> a écrit :


@georges-bayard<https://github.com/georges-bayard> Je te rappelle que tes réponses vont tout droit sur Github 😆
